/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Primary#getNumber <em>Number</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Primary#getParenthesis <em>Parenthesis</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Primary#getVariableUse <em>Variable Use</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Primary#getVariableBinding <em>Variable Binding</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getPrimary()
 * @model
 * @generated
 */
public interface Primary extends Expression
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' containment reference.
   * @see #setNumber(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getPrimary_Number()
   * @model containment="true"
   * @generated
   */
  Expression getNumber();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Primary#getNumber <em>Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' containment reference.
   * @see #getNumber()
   * @generated
   */
  void setNumber(Expression value);

  /**
   * Returns the value of the '<em><b>Parenthesis</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parenthesis</em>' containment reference.
   * @see #setParenthesis(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getPrimary_Parenthesis()
   * @model containment="true"
   * @generated
   */
  Expression getParenthesis();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Primary#getParenthesis <em>Parenthesis</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parenthesis</em>' containment reference.
   * @see #getParenthesis()
   * @generated
   */
  void setParenthesis(Expression value);

  /**
   * Returns the value of the '<em><b>Variable Use</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Use</em>' containment reference.
   * @see #setVariableUse(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getPrimary_VariableUse()
   * @model containment="true"
   * @generated
   */
  Expression getVariableUse();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Primary#getVariableUse <em>Variable Use</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Use</em>' containment reference.
   * @see #getVariableUse()
   * @generated
   */
  void setVariableUse(Expression value);

  /**
   * Returns the value of the '<em><b>Variable Binding</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Binding</em>' containment reference.
   * @see #setVariableBinding(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getPrimary_VariableBinding()
   * @model containment="true"
   * @generated
   */
  Expression getVariableBinding();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Primary#getVariableBinding <em>Variable Binding</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Binding</em>' containment reference.
   * @see #getVariableBinding()
   * @generated
   */
  void setVariableBinding(Expression value);

} // Primary
